{{- if include "identity-service.createSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "identity-service.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "identity-service.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  {{- if .Values.secret.databasePassword }}
  DATABASE_PASSWORD: {{ .Values.secret.databasePassword | quote }}
  {{- else }}
  DATABASE_PASSWORD: ""
  {{- end }}
  {{- if .Values.secret.jwtPrivateKeyB64 }}
  jwt-private-key: {{ .Values.secret.jwtPrivateKeyB64 | b64dec | quote }}
  {{- end }}
  {{- if .Values.secret.jwtPublicKeyB64 }}
  jwt-public-key: {{ .Values.secret.jwtPublicKeyB64 | b64dec | quote }}
  {{- end }}
{{- end }}
