package com.sudo0x.simple.identity.audit.entity;

public enum AuditEventType {
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    ACCOUNT_LOCKED,
    ACCOUNT_UNLOCKED,
    LOGOUT,
    LOGOUT_ALL,
    TOKEN_REFRESHED,
    TOKEN_REUSE_DETECTED,
    PASSWORD_CHANGED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,
    EMAIL_VERIFIED,
    USER_CREATED,
    USER_UPDATED,
    USER_DELETED,
    USER_DISABLED,
    ROLE_ASSIGNED,
    ROLE_REMOVED
}
